# Header
menu:
  Home:
    target:
    href: /
  GitPunch:
    target: _blank
    href: https://gitpunch.com
  War Of Bob:
    target: _blank
    href: https://bob.vfeskov.com
  Platformer:
    target: _blank
    href: https://plat.vfeskov.com
  Back To Top:
    target: _blank
    href: https://www.npmjs.com/package/vanilla-back-to-top
  Link Too Big:
    target: _blank
    href: https://libi.me
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar:
widgets:

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-39039659-3
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
